const tracks=[
 {title:'Moonlit Steps',artist:'Wimusikal Sessions',file:'assets/audio/moonlit-steps.wav',art:'art-1'},
 {title:'Cloudy Notes',artist:'Wimusikal Sessions',file:'assets/audio/cloudy-notes.wav',art:'art-2'},
 {title:'Dreamy Afternoon',artist:'Wimusikal Sessions',file:'assets/audio/dreamy-afternoon.wav',art:'art-3'},
 {title:'Good Energy',artist:'Wimusikal Sessions',file:'assets/audio/good-energy.wav',art:'art-4'}
];
const audio=document.querySelector('#audio'), title=document.querySelector('#title'),artist=document.querySelector('#artist'),progress=document.querySelector('#progress'),current=document.querySelector('#current'),duration=document.querySelector('#duration'),mainPlay=document.querySelector('#mainPlay'),playerArt=document.querySelector('#playerArt'),volume=document.querySelector('#volume');let index=0;
function fmt(s){if(!Number.isFinite(s))return'0:00';return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function load(i,autoplay=false){index=(i+tracks.length)%tracks.length;const t=tracks[index];audio.src=t.file;title.textContent=t.title;artist.textContent=t.artist;playerArt.className=`player-art ${t.art}`;document.querySelectorAll('.album-card').forEach((c,n)=>c.classList.toggle('active',n===index));document.querySelectorAll('.card-play').forEach((b,n)=>b.textContent=n===index&& !audio.paused?'❚❚':'▶');if(autoplay)audio.play().catch(()=>{});}
function toggle(){if(audio.paused){audio.play().catch(()=>{});mainPlay.textContent='❚❚'}else{audio.pause();mainPlay.textContent='▶'}document.querySelectorAll('.card-play').forEach((b,n)=>b.textContent=n===index&&!audio.paused?'❚❚':'▶')}
document.querySelectorAll('[data-play]').forEach(b=>b.addEventListener('click',()=>{load(Number(b.dataset.play));toggle();document.querySelector('#player').scrollIntoView({behavior:'smooth',block:'center'})}));mainPlay.addEventListener('click',toggle);document.querySelector('#next').addEventListener('click',()=>load(index+1,true));document.querySelector('#prev').addEventListener('click',()=>load(index-1,true));audio.addEventListener('ended',()=>load(index+1,true));audio.addEventListener('loadedmetadata',()=>{duration.textContent=fmt(audio.duration)});audio.addEventListener('timeupdate',()=>{current.textContent=fmt(audio.currentTime);progress.value=audio.duration?(audio.currentTime/audio.duration*100):0});progress.addEventListener('input',()=>{if(audio.duration)audio.currentTime=progress.value/100*audio.duration});volume.addEventListener('input',()=>audio.volume=volume.value);audio.volume=.55;load(0);
